<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>SneakOut.LobbyTestBot</AssemblyName>
    <RootNamespace>SneakOut.LobbyTestBot</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Kinguinverse">
      <HintPath>$(InteropDir)/Kinguinverse.dll</HintPath>
    </Reference>
    <Reference Include="Fusion.Runtime">
      <HintPath>$(InteropDir)/Fusion.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(InteropDir)/UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AnimationModule">
      <HintPath>$(InteropDir)/UnityEngine.AnimationModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ScreenCaptureModule">
      <HintPath>$(InteropDir)/UnityEngine.ScreenCaptureModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>$(InteropDir)/UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>$(InteropDir)/UnityEngine.TextRenderingModule.dll</HintPath>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>$(InteropDir)/Unity.TextMeshPro.dll</HintPath>
    </Reference>
    <Reference Include="DOTween">
      <HintPath>$(InteropDir)/DOTween.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
