<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>SneakOut.MummyUnlock</AssemblyName>
    <RootNamespace>SneakOut.MummyUnlock</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Fusion.Runtime">
      <HintPath>$(InteropDir)/Fusion.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(InteropDir)/UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>$(InteropDir)/UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ImageConversionModule">
      <HintPath>$(InteropDir)/UnityEngine.ImageConversionModule.dll</HintPath>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>$(InteropDir)/Unity.TextMeshPro.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets/sarcophagus_mesh.json" LogicalName="SneakOut.MummyUnlock.Assets.sarcophagus_mesh.json" />
    <EmbeddedResource Include="Assets/sarcophagus_texture.jpg" LogicalName="SneakOut.MummyUnlock.Assets.sarcophagus_texture.jpg" />
    <EmbeddedResource Include="Assets/mummy_character_icon.png" LogicalName="SneakOut.MummyUnlock.Assets.mummy_character_icon.png" />
  </ItemGroup>
</Project>
