<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>SneakOut.StartDelayReducer</AssemblyName>
    <RootNamespace>SneakOut.StartDelayReducer</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Fusion.Runtime">
      <HintPath>$(InteropDir)/Fusion.Runtime.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
