<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>SneakOut.ChairWallThrowFix</AssemblyName>
    <RootNamespace>SneakOut.ChairWallThrowFix</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Fusion.Runtime">
      <HintPath>$(InteropDir)/Fusion.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(InteropDir)/UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>$(InteropDir)/UnityEngine.PhysicsModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>$(InteropDir)/UnityEngine.UI.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
