<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>SneakOut.RipperCornerBlinkFix</AssemblyName>
    <RootNamespace>SneakOut.RipperCornerBlinkFix</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Fusion.Runtime">
      <HintPath>$(InteropDir)/Fusion.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="Kinguinverse">
      <HintPath>$(InteropDir)/Kinguinverse.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(InteropDir)/UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>$(InteropDir)/UnityEngine.PhysicsModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AIModule">
      <HintPath>$(InteropDir)/UnityEngine.AIModule.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
