<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>SneakOut.LobbySkillSandbox</AssemblyName>
    <RootNamespace>SneakOut.LobbySkillSandbox</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="EasyPerformantOutline">
      <HintPath>$(InteropDir)/EasyPerformantOutline.dll</HintPath>
    </Reference>
    <Reference Include="Fusion.Runtime">
      <HintPath>$(InteropDir)/Fusion.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(InteropDir)/UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>$(InteropDir)/UnityEngine.InputLegacyModule.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
