<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>SneakOut.UnlockEverything</AssemblyName>
    <RootNamespace>SneakOut.UnlockEverything</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Kinguinverse">
      <HintPath>$(InteropDir)/Kinguinverse.dll</HintPath>
    </Reference>
    <Reference Include="Fusion.Runtime">
      <HintPath>$(InteropDir)/Fusion.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppSystem">
      <HintPath>$(InteropDir)/Il2CppSystem.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppSystem.Net.Http">
      <HintPath>$(InteropDir)/Il2CppSystem.Net.Http.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(InteropDir)/UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>$(InteropDir)/UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="Unity.InputSystem">
      <HintPath>$(InteropDir)/Unity.InputSystem.dll</HintPath>
    </Reference>
    <Reference Include="Unity.RenderPipelines.Core.Runtime">
      <HintPath>$(InteropDir)/Unity.RenderPipelines.Core.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>$(InteropDir)/Unity.TextMeshPro.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
