<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>SneakOut.NetworkHostSelector</AssemblyName>
    <RootNamespace>SneakOut.NetworkHostSelector</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Fusion.Runtime">
      <HintPath>$(InteropDir)/Fusion.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="Fusion.Realtime">
      <HintPath>$(InteropDir)/Fusion.Realtime.dll</HintPath>
    </Reference>
    <Reference Include="Fusion.Sockets">
      <HintPath>$(InteropDir)/Fusion.Sockets.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(InteropDir)/UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>$(InteropDir)/UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>$(InteropDir)/Unity.TextMeshPro.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
