<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>SneakOut.BackgroundLoadingGuard</AssemblyName>
    <RootNamespace>SneakOut.BackgroundLoadingGuard</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(InteropDir)/UnityEngine.CoreModule.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
