<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>SneakOut.RuntimeProfiler</AssemblyName>
    <RootNamespace>SneakOut.RuntimeProfiler</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Kinguinverse">
      <HintPath>$(InteropDir)/Kinguinverse.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(InteropDir)/UnityEngine.CoreModule.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
