<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>SneakOut.FriendInviteUnlock</AssemblyName>
    <RootNamespace>SneakOut.FriendInviteUnlock</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="com.rlabrecque.steamworks.net">
      <HintPath>$(InteropDir)/com.rlabrecque.steamworks.net.dll</HintPath>
    </Reference>
    <Reference Include="Nakama">
      <HintPath>$(InteropDir)/Nakama.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(InteropDir)/UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>$(InteropDir)/UnityEngine.UI.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
